### ISSUE TITLE
unable to subscribe feed via feedly

### ISSUE THREAD

**Issue by kccheung** [room-15/blog#10]
hi, I am unable to subscribe your feed through feedly. Could you fix this?

**Comment by WarrenFaith** [comment]
@kccheung do you get any message from feedly why?

I just checked and added the blog successfully. Both http://room-15.github.io/blog and http://room-15.github.io/blog/rss are working flawless in my opinion.

**Comment by kccheung** [comment]
https://feedly.com/beta/subscription/feed/http://room-15.github.io/blog/atom.xml

works for me.
